# Site settings
title: Stephen Howells
description: "My thoughts on development, design, and culture. My opinions are purely my own and are pretty awesome."
url: "https://stephenhowells.net"
twitter_username: stephenhowells
github_username:  stephenhowells

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
markdown_ext: markdown,md
encoding: "utf-8"
permalink: /:title/
paginate: 5
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'node_modules', 'gulpfile.js', 'package.json', 'scss-lint-config.yml', 's3_website']
timezone: America/Phoenix
kramdown:
  input: GFM
  syntax_highlighter: rouge
  smart_quotes: lsquo,rsquo,ldquo,rdquo
