# Site settings
title: Stephen Howells
description: "Stephen Howells writes about coding, design, and life."
url: "https://stephenhowells.net"
base_url: "StephenHowells.net"
twitter_username: stephenhowells
github_username:  stephenhowells

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
markdown_ext: markdown,md
encoding: "utf-8"
permalink: /:title/
paginate: 5
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'node_modules', 'gulpfile.js', 'package.json', 'scss-lint-config.yml', 'yarn.lock']
timezone: America/Phoenix
kramdown:
  input: GFM
  syntax_highlighter: rouge
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  footnote_backlink: '&#x21A9;&#xFE0E;'
